### ISSUE TITLE
use as a library

### ISSUE THREAD

**Issue by dhowe** [felipelouza/gsufsort#4]
Is it possible to include gsufsort as a lib in another program, passing in input and capturing output all in memory ?

**Comment by felipelouza** [comment]
Hi Daniel, you can use gSACAK API for that: https://github.com/felipelouza/gsa-is?tab=readme-ov-file#api
It might work well if what you need is the generalized enhanced suffix array (SA+DA+LCP).

**Comment by dhowe** [comment]
Thanks!
